import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Check, HeartPulse, Leaf, Menu, Moon, Sparkles, Utensils, X, Zap } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });

const habits = [
  { icon: Utensils, title: "Alimentação equilibrada", text: "Aprende a montar refeições variadas, sem dietas extremas ou culpa." },
  { icon: Zap, title: "Movimento que combina contigo", text: "Encontra atividades agradáveis para ter mais energia no dia a dia." },
  { icon: Moon, title: "Sono e recuperação", text: "Cria uma rotina de descanso que ajude o corpo e a mente a recuperarem." },
];

function Index() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [started, setStarted] = useState(false);
  const close = () => setMenuOpen(false);

  return (
    <main className="min-h-screen overflow-x-hidden bg-[#f7fbf6] text-slate-900">
      <header className="sticky top-0 z-50 border-b border-emerald-950/5 bg-[#f7fbf6]/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8">
          <a href="#inicio" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid size-10 place-items-center rounded-2xl bg-emerald-600 text-white shadow-lg shadow-emerald-600/20"><HeartPulse size={21} /></span><span className="text-xl">VivaLeve</span></a>
          <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a className="hover:text-emerald-700" href="#como-funciona">Como funciona</a><a className="hover:text-emerald-700" href="#habitos">Hábitos</a><a className="hover:text-emerald-700" href="#comece">Começar</a></nav>
          <button onClick={() => setMenuOpen(!menuOpen)} className="rounded-xl p-2 md:hidden" aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <nav className="border-t border-emerald-950/5 px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm font-medium"><a href="#como-funciona" onClick={close}>Como funciona</a><a href="#habitos" onClick={close}>Hábitos</a><a href="#comece" onClick={close}>Começar</a></div></nav>}
      </header>

      <section id="inicio"><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-24">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-4 py-2 text-sm font-semibold text-emerald-800"><Sparkles size={16} /> Saúde antes de tudo</div><h1 className="max-w-3xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">Menos pressão. <span className="text-emerald-600">Mais saúde.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Uma experiência simples para construir hábitos saudáveis, ter mais energia e cuidar de ti de forma sustentável — sem promessas milagrosas.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => setStarted(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-6 py-3.5 font-bold text-white shadow-xl shadow-emerald-600/20 transition hover:-translate-y-0.5 hover:bg-emerald-700">{started ? "Plano iniciado ✓" : "Começar gratuitamente"}{!started && <ArrowRight size={18} />}</button><a href="#como-funciona" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white px-6 py-3.5 font-bold text-slate-700 hover:bg-slate-50">Ver como funciona</a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500"><span className="flex items-center gap-2"><Check className="text-emerald-600" size={17} /> Sem dietas extremas</span><span className="flex items-center gap-2"><Check className="text-emerald-600" size={17} /> Foco em bem-estar</span></div></div>
        <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-5 rounded-[3rem] bg-emerald-200/50 blur-3xl" /><div className="relative overflow-hidden rounded-[2.5rem] bg-emerald-900 p-7 text-white shadow-2xl shadow-emerald-900/20"><div className="flex items-center justify-between"><div><p className="text-sm text-emerald-200">O teu foco hoje</p><h2 className="mt-1 text-2xl font-bold">Cuidar de ti</h2></div><div className="grid size-12 place-items-center rounded-2xl bg-white/10"><Leaf /></div></div><div className="mt-8 space-y-3">{[["Beber água", "Manter hidratação ao longo do dia"], ["Mover o corpo", "Escolher uma atividade que gostes"], ["Fazer uma refeição", "Com variedade e sem culpa"]].map(([title, text]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/10 p-4"><div className="flex items-start gap-3"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-full bg-emerald-400 text-emerald-950"><Check size={15} /></span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-emerald-100/75">{text}</p></div></div></div>)}</div><div className="mt-6 rounded-2xl bg-white p-4 text-slate-800"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Lembrete</p><p className="mt-1 font-semibold">Progresso saudável não precisa ser perfeito.</p></div></div></div>
      </div></section>

      <section id="como-funciona" className="border-y border-emerald-950/5 bg-white"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="font-bold text-emerald-700">COMO FUNCIONA</p><h2 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Transforma a rotina, não a tua relação com o corpo.</h2><p className="mt-4 text-slate-600">O objetivo é apoiar escolhas saudáveis e realistas. Não substitui acompanhamento de profissionais de saúde.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{["Conhece os teus hábitos", "Escolhe pequenas mudanças", "Constrói consistência"].map((title, i) => <div key={title} className="rounded-3xl bg-[#f7fbf6] p-7"><span className="grid size-10 place-items-center rounded-xl bg-emerald-100 font-black text-emerald-700">0{i + 1}</span><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600">Um passo de cada vez, com metas centradas em bem-estar e hábitos que cabem na vida real.</p></div>)}</div></div></section>

      <section id="habitos"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-bold text-emerald-700">PILARES</p><h2 className="mt-2 text-4xl font-black tracking-tight">Hábitos que fazem sentido</h2></div><p className="max-w-md text-slate-600">Não existe uma fórmula igual para toda a gente. O melhor plano é seguro, equilibrado e sustentável.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{habits.map(({ icon: Icon, title, text }) => <article key={title} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="grid size-12 place-items-center rounded-2xl bg-emerald-100 text-emerald-700 group-hover:bg-emerald-600 group-hover:text-white"><Icon /></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

      <section id="comece" className="px-5 pb-20 lg:px-8"><div className="mx-auto max-w-6xl overflow-hidden rounded-[2rem] bg-emerald-700 px-7 py-12 text-white shadow-2xl shadow-emerald-700/20 sm:px-12 lg:flex lg:items-center lg:justify-between lg:py-14"><div className="max-w-2xl"><h2 className="text-3xl font-black sm:text-4xl">Começa pelo próximo hábito, não pela perfeição.</h2><p className="mt-3 text-emerald-50/80">Pequenas escolhas consistentes podem tornar a tua rotina mais saudável.</p></div><button onClick={() => setStarted(true)} className="mt-7 inline-flex shrink-0 items-center gap-2 rounded-2xl bg-white px-6 py-3.5 font-bold text-emerald-800 hover:bg-emerald-50 lg:mt-0">{started ? "Já começaste ✓" : "Começar agora"}<ArrowRight size={18} /></button></div></section>
      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span className="font-bold text-slate-800">VivaLeve</span><span>Conteúdo educativo — não substitui orientação médica ou nutricional.</span></div></footer>
    </main>
  );
}
